import React from 'react';
import Head from "next/head";
import Image from "next/image";

const Layout = ({children}) => {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className="container mx-auto">
                {children}
            </main>

        </div>
    );
};

export default Layout;